---
name: test

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
      branches:
        - main
        - staging

jobs:
  extract_environment:
    outputs:
      environment: ${{ steps.extract_env.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - id: extract_env
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref  }}
          echo ${{ github.base_ref }}
          echo ${{ github.base_ref == 'staging' }}
          echo ${{ github.base_ref == 'main' }}
          if [ ${{ github.base_ref }} == 'staging' ]; then
            echo "environment=staging" >> "$GITHUB_OUTPUT"
            echo "im in staging!"
          elif [ ${{ github.base_ref }}  == 'main' ]; then
            echo "environment=production" >> "$GITHUB_OUTPUT"
            echo "im in production!"
          else
            echo "environment=other" >> "$GITHUB_OUTPUT"
          fi
